#!/bin/bash

#message=''

usage() { echo "Usage: $0 [-m  <string>] [-o <string>]" 1>&2; exit 1;}

if [ $# -gt 0 ]
then
    while getopts ":m:o:h" opt; do #silence errors
        case "${opt}" in
            m)
                message=${OPTARG}
                ;;
			o)
				remoteURL=${OPTARG}
				;;
	    	:)
	        	echo
	    		;;
			*)
                usage
                ;;
        esac
    done
fi

git status # added this

if [[ ! "$(git status --porcelain)" ]]
then
    #echo "nothing to commit, working tree clean";
	exit 1
fi

while [[ ! $message ]]
do
    echo -n "Please enter a commit message: "
    read message
done

echo
echo "This command will run:"
echo "git add ."
echo -n "git commit -m \""
echo -n ${message:0:50}
if [ ${#message} -gt 50 ]
then
    echo "...\""
else
    echo "\""
fi
echo "git push"
echo 

read -r -p "Are you sure? [Y/n] " response

case "$response" in
    [yY][eE][sS]|[yY]) 
		git add .
		git commit -m "$message"

		if [[ $(git config --get remote.origin.url) ]] #catch "fatal: No configured push destination." when there are no added remote origins, typically when creating a new repository on the command line
		then
			git push
		else
			while [[ ! $remoteURL ]]
			do
				echo -n "Please enter the remote origin URL: "
				read remoteURL
			done
			git remote add origin "$remoteURL"
			git push -u origin master
		fi
		;;
    *)
        exit 1
        ;;
esac
